export const Sessions = [
  {
    session_creator: "John Doe",
    session_name: "Belajar Bahasa Korea",
    session_quota: 20,
    session_date: "Senin, 16 Agustus 2024",
    session_begin: "09:20",
    session_end: "12:00",
    session_link: "/belajar-bahasa-inggris",
  },
  {
    session_creator: "Jane Smith",
    session_name: "Workshop ReactJS",
    session_quota: 25,
    session_date: "Selasa, 17 Agustus 2024",
    session_begin: "10:00",
    session_end: "13:00",
    session_link: "/workshop-reactjs",
  },
  {
    session_creator: "Alice Johnson",
    session_name: "Kelas Dasar Python",
    session_quota: 30,
    session_date: "Rabu, 18 Agustus 2024",
    session_begin: "08:00",
    session_end: "11:00",
    session_link: "/kelas-python",
  },
  {
    session_creator: "Bob Brown",
    session_name: "Seminar Teknologi AI",
    session_quota: 50,
    session_date: "Kamis, 19 Agustus 2024",
    session_begin: "09:00",
    session_end: "12:00",
    session_link: "/seminar-ai",
  },
  {
    session_creator: "Charlie Davis",
    session_name: "Pelatihan Data Science",
    session_quota: 40,
    session_date: "Jumat, 20 Agustus 2024",
    session_begin: "13:00",
    session_end: "16:00",
    session_link: "/pelatihan-data-science",
  },
  {
    session_creator: "Diana Evans",
    session_name: "Belajar Bahasa Jepang",
    session_quota: 20,
    session_date: "Sabtu, 21 Agustus 2024",
    session_begin: "10:00",
    session_end: "13:00",
    session_link: "/belajar-bahasa-jepang",
  },
  {
    session_creator: "Frank Green",
    session_name: "Workshop UI/UX Design",
    session_quota: 30,
    session_date: "Minggu, 22 Agustus 2024",
    session_begin: "09:00",
    session_end: "12:00",
    session_link: "/workshop-ui-ux",
  },
  {
    session_creator: "Grace Harris",
    session_name: "Kelas Matematika Dasar",
    session_quota: 25,
    session_date: "Senin, 23 Agustus 2024",
    session_begin: "11:00",
    session_end: "14:00",
    session_link: "/kelas-matematika",
  },
  {
    session_creator: "Hank White",
    session_name: "Pelatihan Web Development",
    session_quota: 35,
    session_date: "Selasa, 24 Agustus 2024",
    session_begin: "09:00",
    session_end: "12:00",
    session_link: "/pelatihan-web-dev",
  },
  {
    session_creator: "Ivy Black",
    session_name: "Seminar Bisnis Online",
    session_quota: 40,
    session_date: "Rabu, 25 Agustus 2024",
    session_begin: "13:00",
    session_end: "16:00",
    session_link: "/seminar-bisnis",
  },
];
